arrowParens: always
breakLongMethodChains: true
endOfLine: lf
importFormatting: oneline
jsxBracketSameLine: true
jsxSingleQuote: false
offsetTernaryExpressions: true
printWidth: 120
proseWrap: preserve
quoteProps: preserve
semi: true
singleQuote: true
trailingComma: es5

tabWidth: 4
useTabs: true
